
    		--======================--
    		--  Projects Analysing  --
    		--======================--
/*
Sales Analysis Performed
1.Total Revenue Analysis
    Calculated the total revenue generated by Tata Motors using selling price and number of units sold.
2.Top-Selling Models
    Identified the vehicle models with the highest number of units sold.
3.Fuel Type Performance
    Compared total sales across different fuel types to determine the best-selling fuel category.
4.Revenue by Vehicle Model
    Analyzed which vehicle models generated the highest revenue.
5.Sales Trends
    Analyzed monthly and yearly sales revenue to identify sales patterns and trends over time.
6.Dealer Performance
    Ranked dealers based on the total number of vehicles sold.
7.City-Wise Sales Analysis
    Compared vehicle sales across different dealer cities to identify high-performing locations.
8.Average Selling Price
    Calculated the average selling price for each vehicle model and compared pricing across models.
9.Customer Color Preferences
    Analyzed vehicle color preferences based on the total number of units sold.
10.Body Type Preference Analysis
    Examined sales by vehicle body type, such as SUV, Sedan, Hatchback, etc.
11.Mileage vs. Sales Analysis
    Examined the relationship between vehicle mileage and the number of units sold.
12.Variant Performance
    Compared different vehicle variants based on their total sales volume.
*/

-- 1. Total revenue tata_motors generated
  SELECT SUM(sale_price * sale_units) AS total_revenue
  FROM sales_details;

-- 2. Top Selling Models
  SELECT vehicle_model,
  	SUM(sale_units) AS units_sold
  FROM sales_details
  GROUP BY vehicle_model
  ORDER BY units_sold DESC;

-- 3. Best Selling fuel type (total_units)
  SELECT v.fuel_type,
  	SUM(s.sale_units) AS best_selling_fuel_type
  FROM sales_details s
  JOIN vehicle_info v
  ON s.vin = v.vin
  GROUP BY v.fuel_type			
  ORDER BY best_selling_fuel_type DESC;

-- 4. Revenue by Vehicle model 
  SELECT vehicle_model,
  	SUM(sale_units * sale_price) AS revenue_by_models
  FROM sales_details
  GROUP BY vehicle_model
  ORDER BY revenue_by_models DESC;

-- 5. Monthly sales and trend 
	-- Monthly sale Trends
  	SELECT YEAR(sale_date) AS sale_year,
  		MONTH(sale_date) AS sale_month,
  		SUM(sale_units * sale_price) AS yearly_revenue
  	FROM sales_details
  	GROUP BY YEAR(sale_date),
  			    MONTH(sale_date)
  	ORDER BY YEAR(sale_date),
  			    MONTH(sale_date);
	-- yearly sale trend
  	SELECT YEAR(sale_date) AS sale_year,
  		SUM(sale_units * sale_price) AS total_revenue
  	FROM sales_details 
  	GROUP BY YEAR(sale_date)
  	ORDER BY sale_year DESC;

-- 6. Dealer performance
  SELECT dealer_id,
  	SUM(sale_units) AS total_unitssales
  FROM sales_details 
  GROUP BY dealer_id
  ORDER BY total_unitssales DESC;

-- 7. City wise sales
  SELECT dealer_city,
  	SUM(sale_units) AS total_unitssales
  FROM sales_details 
  GROUP BY dealer_city
  ORDER BY total_unitssales DESC;

-- 8. Average selling price
  SELECT	vehicle_model,
  	AVG(sale_price) AS avg_price
  FROM sales_details
  GROUP BY vehicle_model
  ORDER BY avg_price DESC;

-- 9. Color preferences
  SELECT vehicle_color,
  	SUM(sale_units) AS total_units
  FROM sales_details
  GROUP BY vehicle_color
  ORDER BY total_units DESC;

--10. Body type preference analysis
  SELECT v.body_type,
  	SUM(s.sale_units) AS total_units
  FROM sales_details s
  JOIN vehicle_info v
  ON s.vin = v.vin
  GROUP BY v.body_type
  ORDER BY total_units DESC;

--11. Mileage vs Sales 
  SELECT v.mileage_kmpl,
  	SUM(s.sale_units) AS total_units
  FROM sales_details s
  JOIN vehicle_info v
    ON s.vin = v.vin
  WHERE v.mileage_kmpl IS NOT NULL
  GROUP BY v.mileage_kmpl
  ORDER BY v.mileage_kmpl DESC;

--12. Variant Performance
  SELECT v.variant,
  	SUM(s.sale_units) AS total_units
  FROM sales_details s
  JOIN vehicle_info v
    ON s.vin = v.vin
  GROUP BY v.variant
  ORDER BY total_units DESC;
